---
deployment:
  tasks:
    - export DEPLOYPATH=/home/imvdeme1/public_html/testvb
    - /bin/cp -R css/ $DEPLOYPATH
    - /bin/cp -R img/ $DEPLOYPATH
    - /bin/cp -R js/ $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp mix-manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH