---
deployment:
  tasks:
    - export DEPLOYPATH=/home/imvdeme1/public_html/votoenblanco.com.mx
    - /bin/cp -R public/css/ $DEPLOYPATH
    - /bin/cp -R public/ckeditor/ $DEPLOYPATH
    - /bin/cp -R public/vendor/ $DEPLOYPATH
    - /bin/cp -R public/img/ $DEPLOYPATH
    - /bin/cp -R public/js/ $DEPLOYPATH
    - /bin/cp -R public/storage/ $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon.ico $DEPLOYPATH
    - /bin/cp public/mix-manifest.json $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH